#!/usr/bin/env python3
"""Extract the Bike Repair statement workbooks into a browser-ready JSON payload."""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date, datetime, time
from pathlib import Path
from typing import Any, Iterable

from openpyxl import load_workbook
from openpyxl.cell.cell import MergedCell
from openpyxl.utils import get_column_letter, range_boundaries


BANNER = "/* GENERATED by extract-statement-steps.py — DO NOT EDIT BY HAND */"
DEFAULT_SOURCE_DIR = "Bike-Repair-Source-Workbooks"
DEFAULT_OUTPUT = "bike-repair-statement-steps.generated.js"

WORKBOOKS = (
    ("Bike-Repair-End.xlsx", "bike-repair-end"),
    ("Bike-Repair-Beg-Module-3.xlsx", "bike-repair-beg-module-3"),
    ("Bike-Repair-Module-3-1.xlsx", "bike-repair-module-3-1"),
    ("Bike-Repair-Module-3-2a.xlsx", "bike-repair-module-3-2a"),
    ("Bike-Repair-Module-3-2b.xlsx", "bike-repair-module-3-2b"),
    ("Bike-Repair-Module-3-3.xlsx", "bike-repair-module-3-3"),
    ("Income-Statement-Steps.xlsx", "income-statement-steps"),
    ("Members-Capital-Steps.xlsx", "members-capital-steps"),
    ("Cash-Flow-Steps.xlsx", "cash-flow-steps"),
    ("Bike-Repair-Module-4-1.xlsx", "bike-repair-module-4-1"),
    ("Bike-Repair-Module-4-1a.xlsx", "bike-repair-module-4-1a"),
    ("Bike-Repair-Module-4-2.xlsx", "bike-repair-module-4-2"),
)

STEP_TAB_RE = re.compile(r"^(\d+)\s*·\s*(.+)$")
FORMULA_REF_RE = re.compile(
    r"(?<![A-Za-z0-9_])"
    r"(\$?[A-Z]{1,3}\$?\d+(?:\s*:\s*\$?[A-Z]{1,3}\$?\d+)?)",
    re.IGNORECASE,
)


class ExtractionError(RuntimeError):
    """Raised when a source workbook cannot be safely extracted."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", default=DEFAULT_SOURCE_DIR)
    parser.add_argument("--out", default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--verify",
        action="store_true",
        help="check the approved accounting invariants before emitting output",
    )
    return parser.parse_args()


def json_value(value: Any, location: str) -> int | float | str | bool | None:
    """Return a value allowed by the extraction contract and strict JSON."""
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, (date, datetime, time)):
        return value.isoformat()
    raise ExtractionError(f"{location} has unsupported cached value {value!r}")


def expand_formula_sources(formula: str) -> list[str]:
    """Flatten cell references and ranges in a ruled-total formula."""
    sources: list[str] = []
    for match in FORMULA_REF_RE.finditer(formula):
        token = match.group(1).replace("$", "").replace(" ", "").upper()
        if ":" not in token:
            sources.append(token)
            continue
        min_col, min_row, max_col, max_row = range_boundaries(token)
        for row in range(min_row, max_row + 1):
            for col in range(min_col, max_col + 1):
                sources.append(f"{get_column_letter(col)}{row}")
    return sources


def merge_anchors(sheet: Any) -> dict[str, str]:
    anchors: dict[str, str] = {}
    for merged_range in sheet.merged_cells.ranges:
        anchors[merged_range.start_cell.coordinate] = str(merged_range)
    return anchors


def extract_sheet(value_sheet: Any, formula_sheet: Any, workbook_name: str) -> dict[str, Any]:
    max_row = max(value_sheet.max_row, formula_sheet.max_row)
    max_col = max(value_sheet.max_column, formula_sheet.max_column)
    anchors = merge_anchors(value_sheet)

    cells: list[dict[str, Any]] = []
    for row_number in range(1, max_row + 1):
        for column_number in range(1, max_col + 1):
            cached_cell = value_sheet.cell(row=row_number, column=column_number)
            if isinstance(cached_cell, MergedCell):
                continue
            formula_cell = formula_sheet.cell(row=row_number, column=column_number)
            coordinate = cached_cell.coordinate
            is_formula = formula_cell.data_type == "f"

            if is_formula and cached_cell.value is None:
                raise ExtractionError(
                    f"{Path(workbook_name).stem}!{value_sheet.title}!{coordinate} has a "
                    "formula but no cached value — open and save the file in Excel, then re-run"
                )

            rule_top = cached_cell.border.top.style
            rule_bottom = cached_cell.border.bottom.style
            if cached_cell.value is None and not rule_top and not rule_bottom:
                continue

            cell_data: dict[str, Any] = {
                "r": row_number,
                "c": column_number,
                "value": json_value(
                    cached_cell.value,
                    f"{Path(workbook_name).stem}!{value_sheet.title}!{coordinate}",
                ),
                "numFmt": cached_cell.number_format or "General",
                "bold": bool(cached_cell.font.bold),
                "italic": bool(cached_cell.font.italic),
                "indent": int(cached_cell.alignment.indent or 0),
                "ruleTop": rule_top,
                "ruleBottom": rule_bottom,
                "merge": anchors.get(coordinate),
            }
            if is_formula and (rule_top or rule_bottom):
                formula = str(formula_cell.value)
                sum_sources = expand_formula_sources(formula)
                if formula.lstrip().upper().startswith("=SUBTOTAL"):
                    sum_sources = [
                        source
                        for source in sum_sources
                        if not (
                            formula_sheet[source].data_type == "f"
                            and str(formula_sheet[source].value)
                            .lstrip()
                            .upper()
                            .startswith("=SUBTOTAL")
                        )
                    ]

                # sumSources is consumed as an unsigned re-sum by the browser.
                # Do not advertise formulas involving subtraction or constants,
                # which that representation cannot reproduce.
                source_total = sum(
                    source_value
                    for source in sum_sources
                    if isinstance(
                        source_value := value_sheet[source].value, (int, float)
                    )
                    and not isinstance(source_value, bool)
                )
                if (
                    isinstance(cached_cell.value, (int, float))
                    and not isinstance(cached_cell.value, bool)
                    and source_total == cached_cell.value
                ):
                    cell_data["sumSources"] = sum_sources
            cells.append(cell_data)

    rows = []
    for row_number in range(1, max_row + 1):
        dimension = value_sheet.row_dimensions[row_number]
        rows.append(
            {
                "outlineLevel": int(dimension.outlineLevel or 0),
                "collapsed": bool(dimension.collapsed),
                "hidden": bool(dimension.hidden),
            }
        )

    default_width = value_sheet.sheet_format.defaultColWidth
    if default_width is None:
        default_width = 13.0
    cols = []
    for column_letter in "ABCDEFGH":
        dimension = value_sheet.column_dimensions.get(column_letter)
        width = dimension.width if dimension is not None and dimension.width is not None else default_width
        cols.append({"width": width})

    tab_match = STEP_TAB_RE.match(value_sheet.title)
    tab_color = value_sheet.sheet_properties.tabColor
    return {
        "name": value_sheet.title,
        "order": int(tab_match.group(1)) if tab_match else None,
        "stepLabel": tab_match.group(2).strip() if tab_match else None,
        "tabColor": tab_color.rgb if tab_color is not None and tab_color.rgb else None,
        "rows": rows,
        "cols": cols,
        "cells": cells,
    }


def extract_workbook(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise ExtractionError(f"source workbook not found: {path}")

    values_book = load_workbook(path, data_only=True, read_only=False)
    formulas_book = load_workbook(path, data_only=False, read_only=False)
    try:
        if values_book.sheetnames != formulas_book.sheetnames:
            raise ExtractionError(f"sheet mismatch between the two reads of {path.name}")
        sheets = [
            extract_sheet(values_book[name], formulas_book[name], path.name)
            for name in values_book.sheetnames
        ]
        return {"sheets": sheets}
    finally:
        values_book.close()
        formulas_book.close()


def extract_all(source_dir: Path) -> dict[str, Any]:
    return {
        "meta": {
            "generated": date.today().isoformat(),
            "source": [filename for filename, _ in WORKBOOKS],
        },
        "workbooks": {
            key: extract_workbook(source_dir / filename)
            for filename, key in WORKBOOKS
        },
    }


def get_sheet(data: dict[str, Any], workbook_key: str, sheet_name: str) -> dict[str, Any]:
    for sheet in data["workbooks"][workbook_key]["sheets"]:
        if sheet["name"] == sheet_name:
            return sheet
    raise ExtractionError(f"extracted sheet not found: {workbook_key}!{sheet_name}")


def row_cells(sheet: dict[str, Any]) -> dict[int, dict[int, dict[str, Any]]]:
    result: dict[int, dict[int, dict[str, Any]]] = {}
    for cell in sheet["cells"]:
        result.setdefault(cell["r"], {})[cell["c"]] = cell
    return result


def statement_data_rows(sheet: dict[str, Any]) -> list[tuple[Any, Any]]:
    grid = row_cells(sheet)
    return [
        (
            grid.get(row, {}).get(2, {}).get("value"),
            grid.get(row, {}).get(4, {}).get("value"),
        )
        for row in range(4, len(sheet["rows"]) + 1)
        if 2 in grid.get(row, {}) or 4 in grid.get(row, {})
    ]


def first_row_pair_mismatch(
    left: list[tuple[Any, Any]], right: list[tuple[Any, Any]]
) -> str | None:
    for offset in range(max(len(left), len(right))):
        left_pair = left[offset] if offset < len(left) else None
        right_pair = right[offset] if offset < len(right) else None
        if left_pair != right_pair:
            return (
                f"data row {offset + 1}: Data copied in={left_pair!r}; "
                f"Working Tab={right_pair!r}"
            )
    return None


def label_rows(
    sheet: dict[str, Any],
    label: str,
    *,
    start: int = 1,
    end: int | None = None,
    contains: bool = False,
) -> list[int]:
    wanted = label.casefold()
    matches: list[int] = []
    for cell in sheet["cells"]:
        if cell["r"] < start or (end is not None and cell["r"] > end):
            continue
        value = cell["value"]
        if not isinstance(value, str):
            continue
        candidate = value.strip().casefold()
        if (wanted in candidate) if contains else (wanted == candidate):
            matches.append(cell["r"])
    return sorted(set(matches))


def value_for_label(
    sheet: dict[str, Any],
    label: str,
    *,
    column: int = 4,
    start: int = 1,
    end: int | None = None,
    contains: bool = False,
    occurrence: int = 0,
) -> int | float:
    rows = label_rows(sheet, label, start=start, end=end, contains=contains)
    if not rows:
        raise ExtractionError(f"label {label!r} not found in extracted sheet {sheet['name']}")
    try:
        row_number = rows[occurrence]
    except IndexError as exc:
        raise ExtractionError(
            f"label {label!r} occurrence {occurrence} not found in extracted sheet {sheet['name']}"
        ) from exc
    cell = row_cells(sheet).get(row_number, {}).get(column)
    value = None if cell is None else cell["value"]
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ExtractionError(
            f"{sheet['name']}!{get_column_letter(column)}{row_number} is not numeric"
        )
    return value


def section_bounds(sheet: dict[str, Any], section: str) -> tuple[int, int]:
    headers = ("CONTRIBUTED", "GENERATED", "WITHDRAWN")
    starts = {header: label_rows(sheet, header) for header in headers}
    if not starts.get(section):
        raise ExtractionError(f"section {section!r} not found in extracted sheet {sheet['name']}")
    start = starts[section][0] + 1
    later_headers = [rows[0] for rows in starts.values() if rows and rows[0] >= start]
    end = min(later_headers) - 1 if later_headers else len(sheet["rows"])
    return start, end


def section_value(
    sheet: dict[str, Any], section: str, label: str, *, occurrence: int = 0
) -> int | float:
    start, end = section_bounds(sheet, section)
    return value_for_label(
        sheet, label, start=start, end=end, occurrence=occurrence
    )


def values_for_matching_rows(
    sheet: dict[str, Any], label_fragment: str, *, column: int = 4
) -> list[int | float]:
    values: list[int | float] = []
    grid = row_cells(sheet)
    for row_number in label_rows(sheet, label_fragment, contains=True):
        cell = grid.get(row_number, {}).get(column)
        value = None if cell is None else cell["value"]
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ExtractionError(
                f"{sheet['name']}!{get_column_letter(column)}{row_number} is not numeric"
            )
        values.append(value)
    return values


def report_invariant(number: int, passed: bool, details: str) -> None:
    status = "PASS" if passed else "FAIL"
    print(f"{status} invariant {number}: {details}")


def verify(data: dict[str, Any]) -> bool:
    """Check the approved invariants using only the extracted payload."""
    income = get_sheet(data, "income-statement-steps", "5 · Format statement")
    members = get_sheet(data, "members-capital-steps", "3 · Make the statement")
    cash_flow = get_sheet(data, "cash-flow-steps", "3 · Make the statement")
    assets = get_sheet(data, "bike-repair-end", "Assets")
    reasons = get_sheet(data, "bike-repair-end", "Reasons")
    balance_sheet = get_sheet(data, "bike-repair-end", "Balance Sheet")

    results: list[bool] = []

    net_income = value_for_label(income, "Net income")
    members_generated_start = section_value(members, "GENERATED", "Balance, June 1, 2026")
    members_generated_end = section_value(members, "GENERATED", "Balance, August 31, 2026")
    reasons_generated_start = section_value(reasons, "GENERATED", "Balance, June 1, 2026")
    reasons_generated_end = section_value(reasons, "GENERATED", "Balance, August 31, 2026")
    members_change = members_generated_end - members_generated_start
    reasons_change = reasons_generated_end - reasons_generated_start
    passed = (
        net_income == 2640
        and members_generated_start == 170
        and members_generated_end == 2810
        and members_change == 2640
        and reasons_generated_start == 170
        and reasons_generated_end == 2810
        and reasons_change == 2640
    )
    results.append(passed)
    report_invariant(
        1,
        passed,
        f"net income={net_income}; Members GENERATED={members_generated_end}-{members_generated_start}={members_change}; "
        f"Reasons GENERATED={reasons_generated_end}-{reasons_generated_start}={reasons_change}; expected=2640",
    )

    ending_cash = value_for_label(cash_flow, "Cash, August 31, 2026")
    cash_start = label_rows(assets, "Cash")[0] + 1
    cash_end = label_rows(assets, "Accounts Receivable")[0] - 1
    assets_ending_cash = value_for_label(
        assets, "Balance, August 31, 2026", start=cash_start, end=cash_end
    )
    balance_sheet_cash = value_for_label(balance_sheet, "Cash")
    passed = (
        ending_cash == 620
        and assets_ending_cash == 620
        and balance_sheet_cash == 620
    )
    results.append(passed)
    report_invariant(
        2,
        passed,
        f"Cash Flow ending={ending_cash}; Assets Cash ending={assets_ending_cash}; Balance Sheet Cash={balance_sheet_cash}; expected=620",
    )

    depreciation_total = value_for_label(income, "Depreciation")
    asset_depreciation = sorted(abs(value) for value in values_for_matching_rows(assets, "Depreciation"))
    reason_depreciation = sorted(abs(value) for value in values_for_matching_rows(reasons, "Depreciation"))
    asset_depreciation_total = sum(asset_depreciation)
    reason_depreciation_total = sum(reason_depreciation)
    expected_classes = [30, 40, 160]
    passed = (
        depreciation_total == 230
        and asset_depreciation == expected_classes
        and reason_depreciation == expected_classes
        and asset_depreciation_total == 230
        and reason_depreciation_total == 230
    )
    results.append(passed)
    report_invariant(
        3,
        passed,
        f"statement depreciation={depreciation_total}; Assets classes={asset_depreciation} total={asset_depreciation_total}; "
        f"Reasons classes={reason_depreciation} total={reason_depreciation_total}; expected=230",
    )

    total_assets = value_for_label(balance_sheet, "Total Assets")
    total_liabilities = value_for_label(balance_sheet, "Total Liabilities")
    contributed_capital = section_value(reasons, "CONTRIBUTED", "Balance, August 31, 2026")
    generated_capital = section_value(reasons, "GENERATED", "Balance, August 31, 2026")
    withdrawn_capital = section_value(reasons, "WITHDRAWN", "Balance, August 31, 2026")
    total_capital = contributed_capital + generated_capital + withdrawn_capital
    passed = (
        total_assets == 4500
        and total_liabilities == 0
        and contributed_capital == 2290
        and generated_capital == 2810
        and withdrawn_capital == -600
        and total_capital == 4500
        and total_assets == total_liabilities + total_capital
    )
    results.append(passed)
    report_invariant(
        4,
        passed,
        f"Assets={total_assets}; Liabilities={total_liabilities}; capital={contributed_capital}+{generated_capital}{withdrawn_capital:+}={total_capital}; expected equation=4500=0+4500",
    )

    ar_june = value_for_label(balance_sheet, "Accounts Receivable", column=3)
    ar_august = value_for_label(balance_sheet, "Accounts Receivable", column=4)
    receivables_increase = ar_august - ar_june
    deposit_june = value_for_label(balance_sheet, "Customer Deposit", column=3)
    deposit_august = value_for_label(balance_sheet, "Customer Deposit", column=4)
    deposit_released = deposit_june - deposit_august
    operating_total = value_for_label(cash_flow, "Cash from operating activities")
    indirect_total = net_income - receivables_increase - deposit_released + depreciation_total
    passed = (
        net_income == 2640
        and receivables_increase == 300
        and deposit_released == 220
        and depreciation_total == 230
        and indirect_total == 2350
        and operating_total == 2350
    )
    results.append(passed)
    report_invariant(
        5,
        passed,
        f"{net_income}-{receivables_increase}-{deposit_released}+{depreciation_total}={indirect_total}; Cash Flow operating={operating_total}; expected=2350",
    )

    # Invariant 6 — the Balance Sheet is hard values (no live formulas since
    # 2026-07-15), so drift protection lives HERE: every BS account line must
    # equal its ledger's ruled dated balances, both columns (Aug 31 = col 4,
    # June 1 = col 3).
    liabilities = get_sheet(data, "bike-repair-end", "Liabilities")
    mismatches: list[str] = []
    checked = 0
    for ledger in (assets, liabilities):
        headers = [c for c in ledger["cells"]
                   if c["c"] == 2 and c["r"] > 1 and c.get("bold") and c.get("value")]
        headers.sort(key=lambda c: c["r"])
        for idx, header in enumerate(headers):
            account = str(header["value"])
            start = header["r"]
            end = headers[idx + 1]["r"] - 1 if idx + 1 < len(headers) else 10_000
            for label, bs_col in (("Balance, August 31, 2026", 4),
                                  ("Balance, June 1, 2026", 3)):
                try:
                    ledger_value = value_for_label(ledger, label, start=start, end=end)
                except Exception:
                    continue  # accounts born mid-season carry no June-1 line
                try:
                    bs_value = value_for_label(balance_sheet, account, column=bs_col)
                except Exception:
                    mismatches.append(f"{account}: no Balance Sheet line found")
                    continue
                checked += 1
                if bs_value != ledger_value:
                    mismatches.append(
                        f"{account} {label}: ledger={ledger_value} vs BS={bs_value}"
                    )
    passed = checked >= 10 and not mismatches
    results.append(passed)
    report_invariant(
        6,
        passed,
        f"Balance Sheet ties to ledger ruled balances: {checked} comparisons"
        + (f"; MISMATCHES: {'; '.join(mismatches)}" if mismatches else ", all equal"),
    )

    # Invariant 7 — the authored start-of-Module-3 snapshot is internally
    # complete, but does not yet contain the two discoveries made in Module 3.
    snapshot_key = "bike-repair-beg-module-3"
    snapshot_assets = get_sheet(data, snapshot_key, "Assets")
    snapshot_liabilities = get_sheet(data, snapshot_key, "Liabilities")
    snapshot_reasons = get_sheet(data, snapshot_key, "Reasons")
    snapshot_balance_sheet = get_sheet(data, snapshot_key, "Balance Sheet")

    def account_section_values(
        sheet: dict[str, Any], account: str
    ) -> tuple[int | float, int | float]:
        grid = row_cells(sheet)
        header_rows = [
            row for row in label_rows(sheet, account)
            if grid.get(row, {}).get(2, {}).get("bold")
        ]
        if not header_rows:
            raise ExtractionError(
                f"bold account header {account!r} not found in extracted sheet {sheet['name']}"
            )
        start = header_rows[0] + 1
        balance_rows = label_rows(
            sheet, "Balance, August 31, 2026", start=start
        )
        if not balance_rows:
            raise ExtractionError(
                f"August 31 balance not found for {account!r} in extracted sheet {sheet['name']}"
            )
        end = balance_rows[0]
        item_total = sum(
            cell["value"]
            for row in range(start, end)
            if (cell := grid.get(row, {}).get(4)) is not None
            and isinstance(cell["value"], (int, float))
            and not isinstance(cell["value"], bool)
        )
        balance = value_for_label(
            sheet, "Balance, August 31, 2026", start=start, end=end
        )
        return item_total, balance

    snapshot_account_expected = {
        "Cash": 620,
        "Right of Use": 650,
        "Parts": 200,
        "Tools & Repair Equipment": 1600,
        "Fixtures": 750,
        "Laptop": 610,
        "Credit Card": 0,
        "Customer Deposit": 0,
    }
    snapshot_account_actual: dict[str, tuple[int | float, int | float]] = {}
    for ledger, accounts in (
        (snapshot_assets, tuple(snapshot_account_expected)[:6]),
        (snapshot_liabilities, tuple(snapshot_account_expected)[6:]),
    ):
        for account in accounts:
            snapshot_account_actual[account] = account_section_values(ledger, account)

    snapshot_reason_expected = {
        "CONTRIBUTED": 2290,
        "GENERATED": 2740,
        "WITHDRAWN": -600,
    }
    snapshot_reason_actual: dict[str, tuple[int | float, int | float]] = {}
    snapshot_reasons_grid = row_cells(snapshot_reasons)
    for section in snapshot_reason_expected:
        start, end = section_bounds(snapshot_reasons, section)
        balance_rows = label_rows(
            snapshot_reasons,
            "Balance, August 31, 2026",
            start=start,
            end=end,
        )
        if not balance_rows:
            raise ExtractionError(
                f"August 31 balance not found for {section!r} in extracted sheet Reasons"
            )
        balance_row = balance_rows[0]
        item_total = sum(
            cell["value"]
            for row in range(start, balance_row)
            if (cell := snapshot_reasons_grid.get(row, {}).get(4)) is not None
            and isinstance(cell["value"], (int, float))
            and not isinstance(cell["value"], bool)
        )
        snapshot_reason_actual[section] = (
            item_total,
            section_value(
                snapshot_reasons, section, "Balance, August 31, 2026"
            ),
        )

    forbidden_hits = [
        f"{sheet['name']}!{get_column_letter(cell['c'])}{cell['r']}={cell['value']!r}"
        for sheet in data["workbooks"][snapshot_key]["sheets"]
        for cell in sheet["cells"]
        if isinstance(cell["value"], str)
        and any(term in cell["value"] for term in ("Accounts Receivable", "Depreciation"))
    ]

    snapshot_bs_expected = {
        "Cash": 1300,
        "Right of Use": 650,
        "Parts": 200,
        "Tools & Repair Equipment": 1200,
        "Fixtures": 750,
        "Laptop": 610,
        "Total Assets": 4710,
        "Credit Card": 2030,
        "Customer Deposit": 220,
        "Total Liabilities": 2250,
        "Contributed": 2290,
        "Generated": 170,
        "Total Member's Capital": 2460,
    }
    snapshot_bs_actual = {
        label: value_for_label(snapshot_balance_sheet, label, column=3)
        for label in snapshot_bs_expected
    }
    snapshot_equation = (
        snapshot_bs_actual["Total Assets"]
        - snapshot_bs_actual["Total Liabilities"]
    )

    snapshot_assets_grid = row_cells(snapshot_assets)
    cash_header = label_rows(snapshot_assets, "Cash")[0]
    cash_boundary = label_rows(
        snapshot_assets,
        "Deposited to open the LLC bank account",
        start=cash_header + 1,
        contains=True,
    )[0]
    june_cash = sum(
        cell["value"]
        for row in range(cash_header + 1, cash_boundary + 1)
        if (cell := snapshot_assets_grid.get(row, {}).get(4)) is not None
        and isinstance(cell["value"], (int, float))
        and not isinstance(cell["value"], bool)
    )
    passed = (
        all(
            item_total == balance == snapshot_account_expected[account]
            for account, (item_total, balance) in snapshot_account_actual.items()
        )
        and all(
            item_total == balance == snapshot_reason_expected[section]
            for section, (item_total, balance) in snapshot_reason_actual.items()
        )
        and not forbidden_hits
        and snapshot_bs_actual == snapshot_bs_expected
        and snapshot_equation == snapshot_bs_actual["Total Member's Capital"]
        and june_cash == snapshot_bs_actual["Cash"] == 1300
    )
    results.append(passed)
    report_invariant(
        7,
        passed,
        f"ledger item sums/balances={snapshot_account_actual}; Reasons item sums/balances={snapshot_reason_actual}; "
        f"forbidden hits={forbidden_hits}; Balance Sheet={snapshot_bs_actual}; "
        f"equation={snapshot_bs_actual['Total Assets']}-{snapshot_bs_actual['Total Liabilities']}={snapshot_equation}; "
        f"Cash through June-1 deposit={june_cash}",
    )

    # Invariant 8 — only the Module 3 receivable and depreciation discoveries
    # separate the authored snapshot balances from the final workbook.
    end_liabilities = liabilities
    continuity_deltas = {
        "Cash": 0,
        "Right of Use": 0,
        "Parts": 0,
        "Tools & Repair Equipment": -160,
        "Fixtures": -40,
        "Laptop": -30,
        "Credit Card": 0,
        "Customer Deposit": 0,
        "CONTRIBUTED": 0,
        "GENERATED": 300 - 230,
        "WITHDRAWN": 0,
    }
    continuity_actual: dict[str, tuple[int | float, int, int | float]] = {}
    for snapshot_ledger, end_ledger, accounts in (
        (snapshot_assets, assets, tuple(snapshot_account_expected)[:6]),
        (snapshot_liabilities, end_liabilities, tuple(snapshot_account_expected)[6:]),
    ):
        for account in accounts:
            snapshot_value = snapshot_account_actual[account][1]
            end_value = account_section_values(end_ledger, account)[1]
            continuity_actual[account] = (
                snapshot_value,
                continuity_deltas[account],
                end_value,
            )
    for section in snapshot_reason_expected:
        continuity_actual[section] = (
            snapshot_reason_actual[section][1],
            continuity_deltas[section],
            section_value(reasons, section, "Balance, August 31, 2026"),
        )

    shared_bs_labels = (
        "Cash",
        "Right of Use",
        "Parts",
        "Tools & Repair Equipment",
        "Fixtures",
        "Laptop",
        "Credit Card",
        "Customer Deposit",
        "Contributed",
        "Generated",
    )
    june_1_continuity = {
        label: (
            value_for_label(snapshot_balance_sheet, label, column=3),
            value_for_label(balance_sheet, label, column=3),
        )
        for label in shared_bs_labels
    }
    passed = (
        all(start + delta == end for start, delta, end in continuity_actual.values())
        and all(snapshot == end for snapshot, end in june_1_continuity.values())
    )
    results.append(passed)
    report_invariant(
        8,
        passed,
        f"Aug-31 continuity (snapshot, delta, End)={continuity_actual}; "
        f"June-1 Balance Sheet (snapshot, End)={june_1_continuity}",
    )

    # Invariant 9 — Module 3-1 is the authored post-periodization state.
    periodized_key = "bike-repair-module-3-1"
    periodized_assets = get_sheet(data, periodized_key, "Assets")
    periodized_liabilities = get_sheet(data, periodized_key, "Liabilities")
    periodized_reasons = get_sheet(data, periodized_key, "Reasons")
    periodized_balance_sheet = get_sheet(data, periodized_key, "Balance Sheet")

    dated_expected = {
        "Cash": (1300, 620),
        "Right of Use": (650, 650),
        "Parts": (200, 200),
        "Tools & Repair Equipment": (1200, 1600),
        "Fixtures": (750, 750),
        "Laptop": (610, 610),
        "Credit Card": (2030, 0),
        "Customer Deposit": (220, 0),
        "CONTRIBUTED": (2290, 2290),
        "GENERATED": (170, 2740),
        "WITHDRAWN": (0, -600),
    }

    def dated_values(
        sheet: dict[str, Any], account: str
    ) -> tuple[int | float, int | float]:
        grid = row_cells(sheet)
        headers = sorted(
            cell["r"]
            for cell in sheet["cells"]
            if cell["c"] == 2 and cell.get("bold") and cell.get("value")
        )
        account_rows = [
            row
            for row in label_rows(sheet, account)
            if grid.get(row, {}).get(2, {}).get("bold")
        ]
        if not account_rows:
            raise ExtractionError(
                f"bold account header {account!r} not found in extracted sheet {sheet['name']}"
            )
        start = account_rows[0] + 1
        later_headers = [row for row in headers if row >= start]
        end = min(later_headers) - 1 if later_headers else len(sheet["rows"])
        return (
            value_for_label(
                sheet,
                "Balance, June 1, 2026",
                start=start,
                end=end,
            ),
            value_for_label(
                sheet,
                "Balance, August 31, 2026",
                start=start,
                end=end,
            ),
        )

    def all_dated_values(workbook_key: str) -> dict[str, tuple[int | float, int | float]]:
        workbook_assets = get_sheet(data, workbook_key, "Assets")
        workbook_liabilities = get_sheet(data, workbook_key, "Liabilities")
        workbook_reasons = get_sheet(data, workbook_key, "Reasons")
        actual: dict[str, tuple[int | float, int | float]] = {}
        for ledger, accounts in (
            (workbook_assets, tuple(dated_expected)[:6]),
            (workbook_liabilities, tuple(dated_expected)[6:8]),
            (workbook_reasons, tuple(dated_expected)[8:]),
        ):
            for account in accounts:
                actual[account] = dated_values(ledger, account)
        return actual

    receivable_key = "bike-repair-module-3-2a"
    depreciation_key = "bike-repair-module-3-2b"
    statement_key = "bike-repair-module-3-3"
    canonical_dated_labels = {
        "Balance, June 1, 2026",
        "Balance, August 31, 2026",
    }
    dated_label_offenders_by_workbook = {
        workbook_key: [
            f"{workbook_key}/{sheet['name']}!B{cell['r']}={cell['value']!r}"
            for sheet in data["workbooks"][workbook_key]["sheets"]
            if sheet["name"] in ("Assets", "Liabilities", "Reasons")
            for cell in sheet["cells"]
            if cell["c"] == 2
            and isinstance(cell["value"], str)
            and cell["value"].startswith("Balance,")
            and cell["value"] not in canonical_dated_labels
        ]
        for workbook_key in (
            periodized_key,
            receivable_key,
            depreciation_key,
            statement_key,
        )
    }
    dated_label_offenders = [
        offender
        for offenders in dated_label_offenders_by_workbook.values()
        for offender in offenders
    ]
    # Audit before exact lookup: a malformed dated label must be reported as an
    # invariant failure (with its exact text), not abort verification as missing.
    periodized_dated_actual = (
        {}
        if dated_label_offenders_by_workbook[periodized_key]
        else all_dated_values(periodized_key)
    )
    periodized_forbidden_hits = [
        f"{sheet['name']}!{get_column_letter(cell['c'])}{cell['r']}={cell['value']!r}"
        for sheet in data["workbooks"][periodized_key]["sheets"]
        for cell in sheet["cells"]
        if isinstance(cell["value"], str)
        and any(
            term in cell["value"]
            for term in ("Accounts Receivable", "Depreciation")
        )
    ]
    periodized_bs_actual = {
        label: value_for_label(periodized_balance_sheet, label, column=3)
        for label in snapshot_bs_expected
    }
    passed = (
        periodized_dated_actual == dated_expected
        and not dated_label_offenders
        and not periodized_forbidden_hits
        and periodized_bs_actual == snapshot_bs_expected
    )
    results.append(passed)
    report_invariant(
        9,
        passed,
        f"dated ledger values (June 1, August 31)={periodized_dated_actual}; "
        f"dated label offenders={dated_label_offenders}; "
        f"forbidden hits={periodized_forbidden_hits}; Balance Sheet={periodized_bs_actual}",
    )

    # Invariant 10 — Module 3-2a records the receivable discovery, before
    # depreciation is discovered or the statement Working Tab is created.
    receivable_sheets = data["workbooks"][receivable_key]["sheets"]
    receivable_sheet_names = [sheet["name"] for sheet in receivable_sheets]
    receivable_name_hygiene_offenders = [
        (name, name.strip())
        for name in receivable_sheet_names
        if name != name.strip()
    ]
    receivable_sheet_names_expected = [
        "Assets",
        "Liabilities",
        "Reasons",
        "Balance Sheet",
    ]
    receivable_structure_ok = (
        receivable_sheet_names == receivable_sheet_names_expected
        and not receivable_name_hygiene_offenders
    )
    receivable_dated_expected = dict(dated_expected)
    receivable_dated_expected["GENERATED"] = (170, 3040)
    receivable_dated_actual = (
        {}
        if (
            not receivable_structure_ok
            or dated_label_offenders_by_workbook[receivable_key]
        )
        else all_dated_values(receivable_key)
    )
    ar_header_rows: list[int] = []
    ar_june_rows: list[int] = []
    ar_august_rows: list[int] = []
    ar_august_value: Any = None
    ridgeline_label = (
        "Repair delivered — Ridgeline Trail Crew, billed net 15 (unpaid)"
    )
    generated_season_bounds: tuple[int, int] | None = None
    ridgeline_rows: list[int] = []
    ridgeline_values: list[Any] = []
    receivable_bs_actual: dict[str, int | float] = {}
    if receivable_structure_ok:
        receivable_assets = get_sheet(data, receivable_key, "Assets")
        receivable_reasons = get_sheet(data, receivable_key, "Reasons")
        receivable_balance_sheet = get_sheet(
            data, receivable_key, "Balance Sheet"
        )
        receivable_assets_grid = row_cells(receivable_assets)
        receivable_header_rows = sorted(
            cell["r"]
            for cell in receivable_assets["cells"]
            if cell["c"] == 2 and cell.get("bold") and cell.get("value")
        )
        ar_header_rows = [
            row
            for row in label_rows(receivable_assets, "Accounts Receivable")
            if receivable_assets_grid.get(row, {}).get(2, {}).get("bold")
        ]
        if len(ar_header_rows) == 1:
            ar_start = ar_header_rows[0] + 1
            later_headers = [
                row for row in receivable_header_rows if row >= ar_start
            ]
            ar_end = (
                min(later_headers) - 1
                if later_headers
                else len(receivable_assets["rows"])
            )
            ar_june_rows = label_rows(
                receivable_assets,
                "Balance, June 1, 2026",
                start=ar_start,
                end=ar_end,
            )
            ar_august_rows = label_rows(
                receivable_assets,
                "Balance, August 31, 2026",
                start=ar_start,
                end=ar_end,
            )
            if len(ar_august_rows) == 1:
                ar_august_value = receivable_assets_grid.get(
                    ar_august_rows[0], {}
                ).get(4, {}).get("value")

        generated_start, generated_end = section_bounds(
            receivable_reasons, "GENERATED"
        )
        receivable_reasons_grid = row_cells(receivable_reasons)
        generated_june_rows = label_rows(
            receivable_reasons,
            "Balance, June 1, 2026",
            start=generated_start,
            end=generated_end,
        )
        generated_august_rows = label_rows(
            receivable_reasons,
            "Balance, August 31, 2026",
            start=generated_start,
            end=generated_end,
        )
        if len(generated_june_rows) == len(generated_august_rows) == 1:
            generated_season_bounds = (
                generated_june_rows[0] + 1,
                generated_august_rows[0] - 1,
            )
            ridgeline_rows = sorted(
                {
                    cell["r"]
                    for cell in receivable_reasons["cells"]
                    if cell["c"] == 2
                    and generated_season_bounds[0]
                    <= cell["r"]
                    <= generated_season_bounds[1]
                    and cell["value"] == ridgeline_label
                }
            )
        ridgeline_values = [
            receivable_reasons_grid.get(row, {}).get(4, {}).get("value")
            for row in ridgeline_rows
        ]
        receivable_bs_actual = {
            label: value_for_label(receivable_balance_sheet, label, column=3)
            for label in snapshot_bs_expected
        }
    depreciation_hits = [
        f"{sheet['name']}!{get_column_letter(cell['c'])}{cell['r']}={cell['value']!r}"
        for sheet in receivable_sheets
        for cell in sheet["cells"]
        if isinstance(cell["value"], str)
        and "Depreciation" in cell["value"]
    ]
    receivable_label_offenders = dated_label_offenders_by_workbook[receivable_key]
    passed = (
        receivable_structure_ok
        and receivable_dated_actual == receivable_dated_expected
        and not receivable_label_offenders
        and len(ar_header_rows) == 1
        and len(ar_august_rows) == 1
        and ar_august_value == 300
        and not ar_june_rows
        and ridgeline_values == [300]
        and not depreciation_hits
        and receivable_bs_actual == snapshot_bs_expected
    )
    results.append(passed)
    report_invariant(
        10,
        passed,
        f"sheets={receivable_sheet_names}; "
        f"name hygiene offenders={receivable_name_hygiene_offenders!r}; "
        f"dated ledger values={receivable_dated_actual}; "
        f"dated label offenders={receivable_label_offenders}; "
        f"Accounts Receivable headers={ar_header_rows}, June rows={ar_june_rows}, "
        f"August rows={ar_august_rows}, value={ar_august_value}; "
        f"GENERATED season bounds={generated_season_bounds}, "
        f"Ridgeline rows/values={list(zip(ridgeline_rows, ridgeline_values))}; "
        f"depreciation hits={depreciation_hits}; Balance Sheet={receivable_bs_actual}",
    )

    # Invariant 11 — every browser re-sum agrees with its cached workbook value.
    resum_checked = 0
    resum_mismatches: list[str] = []
    for workbook_key, workbook in data["workbooks"].items():
        for sheet in workbook["sheets"]:
            grid = row_cells(sheet)
            for cell in sheet["cells"]:
                if "sumSources" not in cell:
                    continue
                cached_value = cell["value"]
                if isinstance(cached_value, bool) or not isinstance(
                    cached_value, (int, float)
                ):
                    continue
                resum_checked += 1
                source_total: int | float = 0
                for source in cell["sumSources"]:
                    match = re.fullmatch(r"([A-Z]+)(\d+)", source)
                    if match is None:
                        resum_mismatches.append(
                            f"{workbook_key}!{sheet['name']}!"
                            f"{get_column_letter(cell['c'])}{cell['r']}: invalid source {source!r}"
                        )
                        continue
                    source_column = 0
                    for character in match.group(1):
                        source_column = source_column * 26 + ord(character) - ord("A") + 1
                    source_cell = grid.get(int(match.group(2)), {}).get(source_column)
                    source_value = None if source_cell is None else source_cell["value"]
                    if isinstance(source_value, (int, float)) and not isinstance(
                        source_value, bool
                    ):
                        source_total += source_value
                if source_total != cached_value:
                    resum_mismatches.append(
                        f"{workbook_key}!{sheet['name']}!"
                        f"{get_column_letter(cell['c'])}{cell['r']}: "
                        f"sources={source_total}, cached={cached_value}"
                    )
    passed = resum_checked > 0 and not resum_mismatches
    results.append(passed)
    report_invariant(
        11,
        passed,
        f"checked={resum_checked}; mismatches={resum_mismatches}",
    )

    # Invariant 12 — Module 3-2b is the completed four-ledger state; Module
    # 3-3 copies from it without changing a single extracted ledger cell.
    depreciation_sheets = data["workbooks"][depreciation_key]["sheets"]
    depreciation_sheet_names = [sheet["name"] for sheet in depreciation_sheets]
    depreciation_name_hygiene_offenders = [
        (name, name.strip())
        for name in depreciation_sheet_names
        if name != name.strip()
    ]
    expected_ledger_sheets = ["Assets", "Liabilities", "Reasons", "Balance Sheet"]
    statement_sheets_by_name = {
        sheet["name"]: sheet for sheet in data["workbooks"][statement_key]["sheets"]
    }
    first_cell_difference: str | None = None
    if depreciation_sheet_names == expected_ledger_sheets:
        for depreciation_sheet in depreciation_sheets:
            sheet_name = depreciation_sheet["name"]
            statement_sheet = statement_sheets_by_name.get(sheet_name)
            if statement_sheet is None:
                first_cell_difference = f"{sheet_name}: missing from {statement_key}"
                break
            left_cells = depreciation_sheet["cells"]
            right_cells = statement_sheet["cells"]
            if left_cells == right_cells:
                continue
            differing_left: dict[str, Any] | None = None
            differing_right: dict[str, Any] | None = None
            for left_cell, right_cell in zip(left_cells, right_cells):
                if left_cell != right_cell:
                    differing_left = left_cell
                    differing_right = right_cell
                    break
            if differing_left is None and len(left_cells) != len(right_cells):
                offset = min(len(left_cells), len(right_cells))
                differing_left = left_cells[offset] if offset < len(left_cells) else None
                differing_right = right_cells[offset] if offset < len(right_cells) else None
            location_cell = differing_left or differing_right
            coordinate = (
                f"{get_column_letter(location_cell['c'])}{location_cell['r']}"
                if location_cell is not None
                else "unknown cell"
            )
            first_cell_difference = (
                f"{sheet_name}!{coordinate}: 2b={differing_left!r}; "
                f"3-3={differing_right!r}"
            )
            break
    passed = (
        depreciation_sheet_names == expected_ledger_sheets
        and not depreciation_name_hygiene_offenders
        and first_cell_difference is None
    )
    results.append(passed)
    report_invariant(
        12,
        passed,
        f"2b sheets={depreciation_sheet_names}; "
        f"name hygiene offenders={depreciation_name_hygiene_offenders!r}; "
        f"first differing sheet/cell={first_cell_difference}",
    )

    # Invariant 13 — Module 3-3 copies the completed GENERATED season slice
    # onto the statement Working Tab and remains continuous with Bike Repair End.
    statement_sheets = data["workbooks"][statement_key]["sheets"]
    statement_sheet_names = [sheet["name"] for sheet in statement_sheets]
    statement_name_hygiene_offenders = [
        (name, name.strip())
        for name in statement_sheet_names
        if name != name.strip()
    ]
    statement_sheet_names_expected = [
        "Assets",
        "Liabilities",
        "Reasons",
        "Balance Sheet",
        "Working Tab",
    ]
    statement_structure_ok = (
        statement_sheet_names == statement_sheet_names_expected
        and not statement_name_hygiene_offenders
    )
    statement_dated_expected = dict(receivable_dated_expected)
    statement_dated_expected.update(
        {
            "Tools & Repair Equipment": (1200, 1440),
            "Fixtures": (750, 710),
            "Laptop": (610, 580),
            "GENERATED": (170, 2810),
        }
    )
    statement_label_offenders = dated_label_offenders_by_workbook[statement_key]
    statement_assets = statement_sheets[0]
    statement_liabilities = statement_sheets[1]
    statement_reasons = statement_sheets[2]
    statement_balance_sheet = statement_sheets[3]
    working_income = statement_sheets[4]
    statement_dated_actual = (
        {}
        if statement_label_offenders
        else {
            account: dated_values(ledger, account)
            for ledger, accounts in (
                (statement_assets, tuple(statement_dated_expected)[:6]),
                (statement_liabilities, tuple(statement_dated_expected)[6:8]),
                (statement_reasons, tuple(statement_dated_expected)[8:]),
            )
            for account in accounts
        }
    )
    statement_asset_depreciation = sorted(
        abs(value)
        for value in values_for_matching_rows(statement_assets, "Depreciation")
    )
    statement_reason_depreciation = sorted(
        abs(value)
        for value in values_for_matching_rows(statement_reasons, "Depreciation")
    )

    working_income_grid = row_cells(working_income)
    title_actual = tuple(
        working_income_grid.get(row, {}).get(2, {}).get("value")
        for row in range(1, 4)
    )
    title_expected = (
        "[Your Name]'s Bike Repair, LLC.",
        "Income Statement",
        "For the period June 1 – August 31, 2026",
    )
    statement_reasons_grid = row_cells(statement_reasons)
    generated_season_rows: list[tuple[Any, Any]] = []
    if not statement_label_offenders:
        generated_start, generated_end = section_bounds(statement_reasons, "GENERATED")
        generated_june_row = label_rows(
            statement_reasons,
            "Balance, June 1, 2026",
            start=generated_start,
            end=generated_end,
        )[0]
        generated_august_row = label_rows(
            statement_reasons,
            "Balance, August 31, 2026",
            start=generated_start,
            end=generated_end,
        )[0]
        generated_season_rows = [
            (
                statement_reasons_grid[row][2]["value"],
                statement_reasons_grid[row][4]["value"],
            )
            for row in range(generated_june_row + 1, generated_august_row)
            if 2 in statement_reasons_grid.get(row, {})
            or 4 in statement_reasons_grid.get(row, {})
        ]
    income_data_rows = statement_data_rows(working_income)
    income_data_sum = sum(
        value
        for _, value in income_data_rows
        if isinstance(value, (int, float)) and not isinstance(value, bool)
    )
    generated_change = (
        statement_dated_actual.get("GENERATED", (None, None))[1]
        - statement_dated_actual.get("GENERATED", (None, None))[0]
        if "GENERATED" in statement_dated_actual
        else None
    )

    end_august_actual: dict[str, int | float] = {}
    for end_ledger, accounts in (
        (assets, tuple(statement_dated_expected)[:6]),
        (liabilities, tuple(statement_dated_expected)[6:8]),
    ):
        for account in accounts:
            end_august_actual[account] = account_section_values(end_ledger, account)[1]
    for section in tuple(statement_dated_expected)[8:]:
        end_august_actual[section] = section_value(
            reasons, section, "Balance, August 31, 2026"
        )
    august_continuity_mismatches = []
    for account in statement_dated_expected:
        statement_value = statement_dated_actual.get(account, (None, None))[1]
        end_value = end_august_actual[account]
        if statement_value != end_value:
            august_continuity_mismatches.append(
                f"{account}: 3-3={statement_value} vs End={end_value}"
            )
    june_1_continuity_mismatches = []
    for label in shared_bs_labels:
        statement_value = value_for_label(statement_balance_sheet, label, column=3)
        end_value = value_for_label(balance_sheet, label, column=3)
        if statement_value != end_value:
            june_1_continuity_mismatches.append(
                f"{label}: 3-3={statement_value} vs End={end_value}"
            )

    passed = (
        statement_structure_ok
        and statement_dated_actual == statement_dated_expected
        and not statement_label_offenders
        and statement_asset_depreciation == [30, 40, 160]
        and statement_reason_depreciation == [30, 40, 160]
        and title_actual == title_expected
        and income_data_rows == generated_season_rows
        and income_data_sum == 2640
        and generated_change == 2640
        and not august_continuity_mismatches
        and not june_1_continuity_mismatches
    )
    results.append(passed)
    report_invariant(
        13,
        passed,
        f"sheets={statement_sheet_names}; "
        f"name hygiene offenders={statement_name_hygiene_offenders!r}; "
        f"dated ledger values={statement_dated_actual}; "
        f"dated label offenders={statement_label_offenders}; "
        f"depreciation Assets={statement_asset_depreciation}, "
        f"Reasons={statement_reason_depreciation}; titles={title_actual}; "
        f"Working Tab rows={income_data_rows}; GENERATED season rows={generated_season_rows}; "
        f"sum/change={income_data_sum}/{generated_change}; "
        f"Aug-31 continuity mismatches={august_continuity_mismatches}; "
        f"June-1 Balance Sheet mismatches={june_1_continuity_mismatches}",
    )

    # Invariant 14 — the income-statement copy stage preserves the authored
    # Module 3-3 Working Tab data rows one-to-one and in order.
    copied_income = get_sheet(data, "income-statement-steps", "0 · Data copied in")
    copied_income_rows = statement_data_rows(copied_income)
    authored_income_rows = statement_data_rows(working_income)
    copied_income_sum = sum(
        value
        for _, value in copied_income_rows
        if isinstance(value, (int, float)) and not isinstance(value, bool)
    )
    authored_income_sum = sum(
        value
        for _, value in authored_income_rows
        if isinstance(value, (int, float)) and not isinstance(value, bool)
    )
    first_income_row_mismatch = first_row_pair_mismatch(
        copied_income_rows, authored_income_rows
    )
    passed = (
        first_income_row_mismatch is None
        and len(copied_income_rows) == 46
        and len(authored_income_rows) == 46
        and copied_income_sum == 2640
        and authored_income_sum == 2640
    )
    results.append(passed)
    report_invariant(
        14,
        passed,
        f"Data copied in rows={len(copied_income_rows)}, sum={copied_income_sum}; "
        f"Working Tab rows={len(authored_income_rows)}, sum={authored_income_sum}; "
        f"first mismatching pair={first_income_row_mismatch}",
    )

    # Invariant 15 — Module 4 tab order and color communicate statement state:
    # blue source ledgers, purple completed statements, and amber working tabs.
    tab_canon = {
        "bike-repair-module-4-1": (
            [
                "Assets",
                "Liabilities",
                "Reasons",
                "Balance Sheet",
                "Income Statement",
                "Working Tab",
            ],
            [
                "FF2563EB",
                "FF2563EB",
                "FF2563EB",
                "FF7030A0",
                "FF7030A0",
                "FFFFC000",
            ],
        ),
        "bike-repair-module-4-1a": (
            [
                "Assets",
                "Liabilities",
                "Reasons",
                "Balance Sheet",
                "Income Statement",
                "St_Members_Capital",
            ],
            [
                "FF2563EB",
                "FF2563EB",
                "FF2563EB",
                "FF7030A0",
                "FF7030A0",
                "FF7030A0",
            ],
        ),
        "bike-repair-module-4-2": (
            [
                "Assets",
                "Liabilities",
                "Reasons",
                "Balance Sheet",
                "Income Statement",
                "St_Members_Capital",
                "Working Tab",
            ],
            [
                "FF2563EB",
                "FF2563EB",
                "FF2563EB",
                "FF7030A0",
                "FF7030A0",
                "FF7030A0",
                "FFFFC000",
            ],
        ),
        "bike-repair-end": (
            [
                "Assets",
                "Liabilities",
                "Reasons",
                "Balance Sheet",
                "Income Statement",
                "St_Members_Capital",
                "Cash_Flow_Statement",
            ],
            [
                "FF2563EB",
                "FF2563EB",
                "FF2563EB",
                "FF7030A0",
                "FF7030A0",
                "FF7030A0",
                "FF7030A0",
            ],
        ),
    }
    tab_actual = {
        workbook_key: (
            [sheet["name"] for sheet in data["workbooks"][workbook_key]["sheets"]],
            [sheet["tabColor"] for sheet in data["workbooks"][workbook_key]["sheets"]],
        )
        for workbook_key in tab_canon
    }
    amber_offenders_4_1a = [
        sheet["name"]
        for sheet in data["workbooks"]["bike-repair-module-4-1a"]["sheets"]
        if sheet["tabColor"] == "FFFFC000"
    ]
    passed = tab_actual == tab_canon and not amber_offenders_4_1a
    results.append(passed)
    report_invariant(
        15,
        passed,
        f"ordered tabs/colors={tab_actual}; 4-1a amber tabs={amber_offenders_4_1a}",
    )

    def first_cell_list_difference(
        left: dict[str, Any], right: dict[str, Any], left_label: str, right_label: str
    ) -> str | None:
        left_cells = left["cells"]
        right_cells = right["cells"]
        for offset in range(max(len(left_cells), len(right_cells))):
            left_cell = left_cells[offset] if offset < len(left_cells) else None
            right_cell = right_cells[offset] if offset < len(right_cells) else None
            if left_cell == right_cell:
                continue
            location_cell = left_cell or right_cell
            coordinate = (
                f"{get_column_letter(location_cell['c'])}{location_cell['r']}"
                if location_cell is not None
                else "unknown cell"
            )
            return (
                f"{left['name']}!{coordinate}: {left_label}={left_cell!r}; "
                f"{right_label}={right_cell!r}"
            )
        return None

    # Invariant 16 — all five shared Module 4 sheets are exact extracted-cell
    # copies of the final workbook, across all three authored snapshots.
    shared_module_4_sheets = (
        "Assets",
        "Liabilities",
        "Reasons",
        "Balance Sheet",
        "Income Statement",
    )
    shared_sheet_differences: dict[str, str | None] = {}
    for workbook_key in (
        "bike-repair-module-4-1",
        "bike-repair-module-4-1a",
        "bike-repair-module-4-2",
    ):
        first_difference: str | None = None
        for sheet_name in shared_module_4_sheets:
            first_difference = first_cell_list_difference(
                get_sheet(data, workbook_key, sheet_name),
                get_sheet(data, "bike-repair-end", sheet_name),
                workbook_key,
                "bike-repair-end",
            )
            if first_difference is not None:
                break
        shared_sheet_differences[workbook_key] = first_difference
    passed = all(
        difference is None for difference in shared_sheet_differences.values()
    )
    results.append(passed)
    report_invariant(
        16,
        passed,
        f"first differing shared sheet/cell={shared_sheet_differences}",
    )

    def data_pairs_after_period(sheet: dict[str, Any]) -> list[tuple[Any, Any]]:
        period_rows = label_rows(sheet, "For the period", contains=True)
        if len(period_rows) != 1:
            raise ExtractionError(
                f"expected one period title in extracted sheet {sheet['name']}; "
                f"found rows {period_rows}"
            )
        grid = row_cells(sheet)
        return [
            (
                grid.get(row, {}).get(2, {}).get("value"),
                grid.get(row, {}).get(4, {}).get("value"),
            )
            for row in range(period_rows[0] + 1, len(sheet["rows"]) + 1)
            if 2 in grid.get(row, {}) or 4 in grid.get(row, {})
        ]

    def section_item_sum(sheet: dict[str, Any], section: str) -> int | float:
        start, end = section_bounds(sheet, section)
        grid = row_cells(sheet)
        return sum(
            cell["value"]
            for row in range(start, end + 1)
            if not str(grid.get(row, {}).get(2, {}).get("value", "")).startswith(
                "Balance,"
            )
            if (cell := grid.get(row, {}).get(4)) is not None
            and isinstance(cell["value"], (int, float))
            and not isinstance(cell["value"], bool)
        )

    # Invariant 17 — Module 4-1 copies the complete member-capital ledger into
    # its amber Working Tab, including the mid-season birth of WITHDRAWN.
    working_members = get_sheet(data, "bike-repair-module-4-1", "Working Tab")
    copied_members = get_sheet(data, "members-capital-steps", "0 · Data copied in")
    working_members_rows = data_pairs_after_period(working_members)
    copied_members_rows = data_pairs_after_period(copied_members)
    first_members_row_mismatch = first_row_pair_mismatch(
        copied_members_rows, working_members_rows
    )
    member_item_sums = {
        section: section_item_sum(working_members, section)
        for section in ("CONTRIBUTED", "GENERATED", "WITHDRAWN")
    }
    working_generated_start = section_value(
        working_members, "GENERATED", "Balance, June 1, 2026"
    )
    working_generated_end = section_value(
        working_members, "GENERATED", "Balance, August 31, 2026"
    )
    withdrawn_start, withdrawn_end = section_bounds(working_members, "WITHDRAWN")
    withdrawn_june_rows = label_rows(
        working_members,
        "Balance, June 1, 2026",
        start=withdrawn_start,
        end=withdrawn_end,
    )
    passed = (
        first_members_row_mismatch is None
        and member_item_sums
        == {"CONTRIBUTED": 2290, "GENERATED": 2810, "WITHDRAWN": -600}
        and working_generated_start == 170
        and working_generated_end == 2810
        and working_generated_end - working_generated_start == 2640
        and not withdrawn_june_rows
    )
    results.append(passed)
    report_invariant(
        17,
        passed,
        f"4-1/copy rows={len(working_members_rows)}/{len(copied_members_rows)}; "
        f"first mismatching pair={first_members_row_mismatch}; item sums={member_item_sums}; "
        f"GENERATED={working_generated_end}-{working_generated_start}="
        f"{working_generated_end - working_generated_start}; "
        f"WITHDRAWN June-1 rows={withdrawn_june_rows}",
    )

    # Invariant 18 — Module 4-2 copies the Cash ledger's exact 28-row season
    # slice to its amber Working Tab, and that slice explains the cash change.
    working_cash = get_sheet(data, "bike-repair-module-4-2", "Working Tab")
    copied_cash = get_sheet(data, "cash-flow-steps", "0 · Data copied in")
    working_cash_rows = data_pairs_after_period(working_cash)
    copied_cash_rows = data_pairs_after_period(copied_cash)
    first_cash_row_mismatch = first_row_pair_mismatch(
        copied_cash_rows, working_cash_rows
    )
    working_cash_values = [
        value
        for _, value in working_cash_rows
        if isinstance(value, (int, float)) and not isinstance(value, bool)
    ]
    module_4_2_assets = get_sheet(data, "bike-repair-module-4-2", "Assets")
    module_4_2_assets_grid = row_cells(module_4_2_assets)
    cash_header_row = label_rows(module_4_2_assets, "Cash")[0]
    cash_end_row = label_rows(module_4_2_assets, "Accounts Receivable")[0] - 1
    cash_june_rows = [
        row
        for row in label_rows(
            module_4_2_assets,
            "Balance, June 1, 2026",
            start=cash_header_row + 1,
            end=cash_end_row,
        )
        if module_4_2_assets_grid.get(row, {}).get(4, {}).get("value") == 1300
    ]
    cash_august_rows = [
        row
        for row in label_rows(
            module_4_2_assets,
            "Balance, August 31, 2026",
            start=cash_header_row + 1,
            end=cash_end_row,
        )
        if module_4_2_assets_grid.get(row, {}).get(4, {}).get("value") == 620
    ]
    cash_season_values: list[int | float] = []
    if len(cash_june_rows) == len(cash_august_rows) == 1:
        cash_season_values = [
            cell["value"]
            for row in range(cash_june_rows[0] + 1, cash_august_rows[0])
            if (cell := module_4_2_assets_grid.get(row, {}).get(4)) is not None
            and isinstance(cell["value"], (int, float))
            and not isinstance(cell["value"], bool)
        ]
    passed = (
        first_cash_row_mismatch is None
        and len(working_cash_values) == 28
        and sum(working_cash_values) == -680
        and len(cash_june_rows) == len(cash_august_rows) == 1
        and len(cash_season_values) == 28
        and sum(cash_season_values) == -680
        and working_cash_values == cash_season_values
    )
    results.append(passed)
    report_invariant(
        18,
        passed,
        f"4-2/copy rows={len(working_cash_rows)}/{len(copied_cash_rows)}, "
        f"first mismatching pair={first_cash_row_mismatch}; Working values "
        f"count/sum={len(working_cash_values)}/{sum(working_cash_values)}; "
        f"Cash bounds={cash_june_rows}/{cash_august_rows}; season count/sum="
        f"{len(cash_season_values)}/{sum(cash_season_values)}; "
        f"ordered values equal={working_cash_values == cash_season_values}",
    )

    def normalized_cells_without_llc_title(
        sheet: dict[str, Any]
    ) -> list[dict[str, Any]]:
        grid = row_cells(sheet)
        first_label = grid.get(1, {}).get(2, {}).get("value")
        dropped_rows = (
            1
            if isinstance(first_label, str)
            and first_label.endswith("Bike Repair, LLC.")
            else 0
        )

        def shift_coordinate(coordinate: str) -> str:
            match = re.fullmatch(r"([A-Z]+)(\d+)", coordinate)
            if match is None:
                return coordinate
            return f"{match.group(1)}{int(match.group(2)) - dropped_rows}"

        normalized: list[dict[str, Any]] = []
        for cell in sheet["cells"]:
            if cell["r"] <= dropped_rows:
                continue
            normalized_cell = dict(cell)
            normalized_cell["r"] -= dropped_rows
            if normalized_cell.get("merge"):
                normalized_cell["merge"] = re.sub(
                    r"([A-Z]+)(\d+)",
                    lambda match: (
                        f"{match.group(1)}"
                        f"{int(match.group(2)) - dropped_rows}"
                    ),
                    normalized_cell["merge"],
                )
            if "sumSources" in normalized_cell:
                normalized_cell["sumSources"] = [
                    shift_coordinate(source)
                    for source in normalized_cell["sumSources"]
                ]
            normalized.append(normalized_cell)
        return normalized

    # Invariant 19 — the completed member-capital statement persists unchanged
    # through Module 4 and matches the guided statement modulo End's LLC row.
    end_members = get_sheet(data, "bike-repair-end", "St_Members_Capital")
    module_4_1a_members = get_sheet(
        data, "bike-repair-module-4-1a", "St_Members_Capital"
    )
    module_4_2_members = get_sheet(
        data, "bike-repair-module-4-2", "St_Members_Capital"
    )
    module_4_1a_members_difference = first_cell_list_difference(
        module_4_1a_members,
        end_members,
        "bike-repair-module-4-1a",
        "bike-repair-end",
    )
    module_4_2_members_difference = first_cell_list_difference(
        module_4_2_members,
        end_members,
        "bike-repair-module-4-2",
        "bike-repair-end",
    )
    guided_members_normalized = normalized_cells_without_llc_title(members)
    end_members_normalized = normalized_cells_without_llc_title(end_members)
    first_guided_members_difference: str | None = None
    for offset in range(
        max(len(guided_members_normalized), len(end_members_normalized))
    ):
        guided_cell = (
            guided_members_normalized[offset]
            if offset < len(guided_members_normalized)
            else None
        )
        end_cell = (
            end_members_normalized[offset]
            if offset < len(end_members_normalized)
            else None
        )
        if guided_cell != end_cell:
            first_guided_members_difference = (
                f"normalized cell {offset + 1}: steps={guided_cell!r}; "
                f"End={end_cell!r}"
            )
            break
    total_members_june = value_for_label(
        end_members, "Total Member's Capital, June 1, 2026"
    )
    total_members_august = value_for_label(
        end_members, "Total Member's Capital, August 31, 2026"
    )
    passed = (
        module_4_1a_members_difference is None
        and module_4_2_members_difference is None
        and first_guided_members_difference is None
        and total_members_june == 2460
        and total_members_august == 4500
    )
    results.append(passed)
    report_invariant(
        19,
        passed,
        f"4-1a first difference={module_4_1a_members_difference}; "
        f"4-2 first difference={module_4_2_members_difference}; "
        f"steps/End normalized cells={len(guided_members_normalized)}/"
        f"{len(end_members_normalized)}, first difference={first_guided_members_difference}; "
        f"total capital June/August={total_members_june}/{total_members_august}",
    )

    # Invariant 20 — the guided cash-flow statement matches End modulo its LLC
    # row and carries the approved operating, investing, financing, and cash totals.
    end_cash_flow = get_sheet(data, "bike-repair-end", "Cash_Flow_Statement")
    guided_cash_flow_normalized = normalized_cells_without_llc_title(cash_flow)
    end_cash_flow_normalized = normalized_cells_without_llc_title(end_cash_flow)
    first_guided_cash_flow_difference: str | None = None
    for offset in range(
        max(len(guided_cash_flow_normalized), len(end_cash_flow_normalized))
    ):
        guided_cell = (
            guided_cash_flow_normalized[offset]
            if offset < len(guided_cash_flow_normalized)
            else None
        )
        end_cell = (
            end_cash_flow_normalized[offset]
            if offset < len(end_cash_flow_normalized)
            else None
        )
        if guided_cell != end_cell:
            first_guided_cash_flow_difference = (
                f"normalized cell {offset + 1}: steps={guided_cell!r}; "
                f"End={end_cell!r}"
            )
            break
    cash_flow_totals = {
        "operating": value_for_label(
            end_cash_flow, "Cash from operating activities"
        ),
        "investing": value_for_label(
            end_cash_flow, "Cash used in investing activities"
        ),
        "financing": value_for_label(
            end_cash_flow, "Cash used in financing activities"
        ),
        "net change": value_for_label(end_cash_flow, "Net change in cash"),
        "ending cash": value_for_label(end_cash_flow, "Cash, August 31, 2026"),
    }
    passed = (
        first_guided_cash_flow_difference is None
        and cash_flow_totals
        == {
            "operating": 2350,
            "investing": -400,
            "financing": -2630,
            "net change": -680,
            "ending cash": 620,
        }
    )
    results.append(passed)
    report_invariant(
        20,
        passed,
        f"steps/End normalized cells={len(guided_cash_flow_normalized)}/"
        f"{len(end_cash_flow_normalized)}, first difference="
        f"{first_guided_cash_flow_difference}; totals={cash_flow_totals}",
    )

    return all(results)


def emit(data: dict[str, Any], output_path: Path) -> None:
    payload = json.dumps(data, ensure_ascii=False, allow_nan=False, indent=2)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        f"{BANNER}\nwindow.BR_STMT_DATA = {payload};\n", encoding="utf-8"
    )


def main() -> int:
    args = parse_args()
    try:
        data = extract_all(Path(args.source_dir))
        if args.verify and not verify(data):
            print("Verification failed; output was not emitted.", file=sys.stderr)
            return 1
        emit(data, Path(args.out))
        print(f"Wrote {args.out}")
        return 0
    except (ExtractionError, OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
