#!/usr/bin/env python3
"""Extract the Bike Repair statement workbooks into a browser-ready JSON payload."""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date, datetime, time
from pathlib import Path
from typing import Any, Iterable

from openpyxl import load_workbook
from openpyxl.cell.cell import MergedCell
from openpyxl.utils import get_column_letter, range_boundaries


BANNER = "/* GENERATED by extract-statement-steps.py — DO NOT EDIT BY HAND */"
DEFAULT_SOURCE_DIR = "Bike-Repair-Source-Workbooks"
DEFAULT_OUTPUT = "bike-repair-statement-steps.generated.js"

WORKBOOKS = (
    ("Bike-Repair-End.xlsx", "bike-repair-end"),
    ("Income-Statement-Steps.xlsx", "income-statement-steps"),
    ("Members-Capital-Steps.xlsx", "members-capital-steps"),
    ("Cash-Flow-Steps.xlsx", "cash-flow-steps"),
)

STEP_TAB_RE = re.compile(r"^(\d+)\s*·\s*(.+)$")
FORMULA_REF_RE = re.compile(
    r"(?<![A-Za-z0-9_])"
    r"(\$?[A-Z]{1,3}\$?\d+(?:\s*:\s*\$?[A-Z]{1,3}\$?\d+)?)",
    re.IGNORECASE,
)


class ExtractionError(RuntimeError):
    """Raised when a source workbook cannot be safely extracted."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", default=DEFAULT_SOURCE_DIR)
    parser.add_argument("--out", default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--verify",
        action="store_true",
        help="check the approved accounting invariants before emitting output",
    )
    return parser.parse_args()


def json_value(value: Any, location: str) -> int | float | str | bool | None:
    """Return a value allowed by the extraction contract and strict JSON."""
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, (date, datetime, time)):
        return value.isoformat()
    raise ExtractionError(f"{location} has unsupported cached value {value!r}")


def expand_formula_sources(formula: str) -> list[str]:
    """Flatten cell references and ranges in a ruled-total formula."""
    sources: list[str] = []
    for match in FORMULA_REF_RE.finditer(formula):
        token = match.group(1).replace("$", "").replace(" ", "").upper()
        if ":" not in token:
            sources.append(token)
            continue
        min_col, min_row, max_col, max_row = range_boundaries(token)
        for row in range(min_row, max_row + 1):
            for col in range(min_col, max_col + 1):
                sources.append(f"{get_column_letter(col)}{row}")
    return sources


def merge_anchors(sheet: Any) -> dict[str, str]:
    anchors: dict[str, str] = {}
    for merged_range in sheet.merged_cells.ranges:
        anchors[merged_range.start_cell.coordinate] = str(merged_range)
    return anchors


def extract_sheet(value_sheet: Any, formula_sheet: Any, workbook_name: str) -> dict[str, Any]:
    max_row = max(value_sheet.max_row, formula_sheet.max_row)
    max_col = max(value_sheet.max_column, formula_sheet.max_column)
    anchors = merge_anchors(value_sheet)

    cells: list[dict[str, Any]] = []
    for row_number in range(1, max_row + 1):
        for column_number in range(1, max_col + 1):
            cached_cell = value_sheet.cell(row=row_number, column=column_number)
            if isinstance(cached_cell, MergedCell):
                continue
            formula_cell = formula_sheet.cell(row=row_number, column=column_number)
            coordinate = cached_cell.coordinate
            is_formula = formula_cell.data_type == "f"

            if is_formula and cached_cell.value is None:
                raise ExtractionError(
                    f"{Path(workbook_name).stem}!{value_sheet.title}!{coordinate} has a "
                    "formula but no cached value — open and save the file in Excel, then re-run"
                )

            rule_top = cached_cell.border.top.style
            rule_bottom = cached_cell.border.bottom.style
            if cached_cell.value is None and not rule_top and not rule_bottom:
                continue

            cell_data: dict[str, Any] = {
                "r": row_number,
                "c": column_number,
                "value": json_value(
                    cached_cell.value,
                    f"{Path(workbook_name).stem}!{value_sheet.title}!{coordinate}",
                ),
                "numFmt": cached_cell.number_format or "General",
                "bold": bool(cached_cell.font.bold),
                "italic": bool(cached_cell.font.italic),
                "indent": int(cached_cell.alignment.indent or 0),
                "ruleTop": rule_top,
                "ruleBottom": rule_bottom,
                "merge": anchors.get(coordinate),
            }
            if is_formula and (rule_top or rule_bottom):
                cell_data["sumSources"] = expand_formula_sources(str(formula_cell.value))
            cells.append(cell_data)

    rows = []
    for row_number in range(1, max_row + 1):
        dimension = value_sheet.row_dimensions[row_number]
        rows.append(
            {
                "outlineLevel": int(dimension.outlineLevel or 0),
                "collapsed": bool(dimension.collapsed),
                "hidden": bool(dimension.hidden),
            }
        )

    default_width = value_sheet.sheet_format.defaultColWidth
    if default_width is None:
        default_width = 13.0
    cols = []
    for column_letter in "ABCDEFGH":
        dimension = value_sheet.column_dimensions.get(column_letter)
        width = dimension.width if dimension is not None and dimension.width is not None else default_width
        cols.append({"width": width})

    tab_match = STEP_TAB_RE.match(value_sheet.title)
    return {
        "name": value_sheet.title,
        "order": int(tab_match.group(1)) if tab_match else None,
        "stepLabel": tab_match.group(2).strip() if tab_match else None,
        "rows": rows,
        "cols": cols,
        "cells": cells,
    }


def extract_workbook(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise ExtractionError(f"source workbook not found: {path}")

    values_book = load_workbook(path, data_only=True, read_only=False)
    formulas_book = load_workbook(path, data_only=False, read_only=False)
    try:
        if values_book.sheetnames != formulas_book.sheetnames:
            raise ExtractionError(f"sheet mismatch between the two reads of {path.name}")
        sheets = [
            extract_sheet(values_book[name], formulas_book[name], path.name)
            for name in values_book.sheetnames
        ]
        return {"sheets": sheets}
    finally:
        values_book.close()
        formulas_book.close()


def extract_all(source_dir: Path) -> dict[str, Any]:
    return {
        "meta": {
            "generated": date.today().isoformat(),
            "source": [filename for filename, _ in WORKBOOKS],
        },
        "workbooks": {
            key: extract_workbook(source_dir / filename)
            for filename, key in WORKBOOKS
        },
    }


def get_sheet(data: dict[str, Any], workbook_key: str, sheet_name: str) -> dict[str, Any]:
    for sheet in data["workbooks"][workbook_key]["sheets"]:
        if sheet["name"] == sheet_name:
            return sheet
    raise ExtractionError(f"extracted sheet not found: {workbook_key}!{sheet_name}")


def row_cells(sheet: dict[str, Any]) -> dict[int, dict[int, dict[str, Any]]]:
    result: dict[int, dict[int, dict[str, Any]]] = {}
    for cell in sheet["cells"]:
        result.setdefault(cell["r"], {})[cell["c"]] = cell
    return result


def label_rows(
    sheet: dict[str, Any],
    label: str,
    *,
    start: int = 1,
    end: int | None = None,
    contains: bool = False,
) -> list[int]:
    wanted = label.casefold()
    matches: list[int] = []
    for cell in sheet["cells"]:
        if cell["r"] < start or (end is not None and cell["r"] > end):
            continue
        value = cell["value"]
        if not isinstance(value, str):
            continue
        candidate = value.strip().casefold()
        if (wanted in candidate) if contains else (wanted == candidate):
            matches.append(cell["r"])
    return sorted(set(matches))


def value_for_label(
    sheet: dict[str, Any],
    label: str,
    *,
    column: int = 4,
    start: int = 1,
    end: int | None = None,
    contains: bool = False,
    occurrence: int = 0,
) -> int | float:
    rows = label_rows(sheet, label, start=start, end=end, contains=contains)
    if not rows:
        raise ExtractionError(f"label {label!r} not found in extracted sheet {sheet['name']}")
    try:
        row_number = rows[occurrence]
    except IndexError as exc:
        raise ExtractionError(
            f"label {label!r} occurrence {occurrence} not found in extracted sheet {sheet['name']}"
        ) from exc
    cell = row_cells(sheet).get(row_number, {}).get(column)
    value = None if cell is None else cell["value"]
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ExtractionError(
            f"{sheet['name']}!{get_column_letter(column)}{row_number} is not numeric"
        )
    return value


def section_bounds(sheet: dict[str, Any], section: str) -> tuple[int, int]:
    headers = ("CONTRIBUTED", "GENERATED", "WITHDRAWN")
    starts = {header: label_rows(sheet, header) for header in headers}
    if not starts.get(section):
        raise ExtractionError(f"section {section!r} not found in extracted sheet {sheet['name']}")
    start = starts[section][0] + 1
    later_headers = [rows[0] for rows in starts.values() if rows and rows[0] >= start]
    end = min(later_headers) - 1 if later_headers else len(sheet["rows"])
    return start, end


def section_value(
    sheet: dict[str, Any], section: str, label: str, *, occurrence: int = 0
) -> int | float:
    start, end = section_bounds(sheet, section)
    return value_for_label(
        sheet, label, start=start, end=end, occurrence=occurrence
    )


def values_for_matching_rows(
    sheet: dict[str, Any], label_fragment: str, *, column: int = 4
) -> list[int | float]:
    values: list[int | float] = []
    grid = row_cells(sheet)
    for row_number in label_rows(sheet, label_fragment, contains=True):
        cell = grid.get(row_number, {}).get(column)
        value = None if cell is None else cell["value"]
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ExtractionError(
                f"{sheet['name']}!{get_column_letter(column)}{row_number} is not numeric"
            )
        values.append(value)
    return values


def report_invariant(number: int, passed: bool, details: str) -> None:
    status = "PASS" if passed else "FAIL"
    print(f"{status} invariant {number}: {details}")


def verify(data: dict[str, Any]) -> bool:
    """Check the approved invariants using only the extracted payload."""
    income = get_sheet(data, "income-statement-steps", "5 · Format statement")
    members = get_sheet(data, "members-capital-steps", "3 · Make the statement")
    cash_flow = get_sheet(data, "cash-flow-steps", "3 · Make the statement")
    assets = get_sheet(data, "bike-repair-end", "Assets")
    reasons = get_sheet(data, "bike-repair-end", "Reasons")
    balance_sheet = get_sheet(data, "bike-repair-end", "Balance Sheet")

    results: list[bool] = []

    net_income = value_for_label(income, "Net income")
    members_generated_start = section_value(members, "GENERATED", "Balance, June 1, 2026")
    members_generated_end = section_value(members, "GENERATED", "Balance, August 31, 2026")
    reasons_generated_start = section_value(reasons, "GENERATED", "Balance, June 1, 2026")
    reasons_generated_end = section_value(reasons, "GENERATED", "Balance, August 31, 2026")
    members_change = members_generated_end - members_generated_start
    reasons_change = reasons_generated_end - reasons_generated_start
    passed = (
        net_income == 2640
        and members_generated_start == 170
        and members_generated_end == 2810
        and members_change == 2640
        and reasons_generated_start == 170
        and reasons_generated_end == 2810
        and reasons_change == 2640
    )
    results.append(passed)
    report_invariant(
        1,
        passed,
        f"net income={net_income}; Members GENERATED={members_generated_end}-{members_generated_start}={members_change}; "
        f"Reasons GENERATED={reasons_generated_end}-{reasons_generated_start}={reasons_change}; expected=2640",
    )

    ending_cash = value_for_label(cash_flow, "Cash, August 31, 2026")
    cash_start = label_rows(assets, "Cash")[0] + 1
    cash_end = label_rows(assets, "Accounts Receivable")[0] - 1
    assets_ending_cash = value_for_label(
        assets, "Balance, August 31, 2026", start=cash_start, end=cash_end
    )
    balance_sheet_cash = value_for_label(balance_sheet, "Cash")
    passed = (
        ending_cash == 620
        and assets_ending_cash == 620
        and balance_sheet_cash == 620
    )
    results.append(passed)
    report_invariant(
        2,
        passed,
        f"Cash Flow ending={ending_cash}; Assets Cash ending={assets_ending_cash}; Balance Sheet Cash={balance_sheet_cash}; expected=620",
    )

    depreciation_total = value_for_label(income, "Depreciation")
    asset_depreciation = sorted(abs(value) for value in values_for_matching_rows(assets, "Depreciation"))
    reason_depreciation = sorted(abs(value) for value in values_for_matching_rows(reasons, "Depreciation"))
    asset_depreciation_total = sum(asset_depreciation)
    reason_depreciation_total = sum(reason_depreciation)
    expected_classes = [30, 40, 160]
    passed = (
        depreciation_total == 230
        and asset_depreciation == expected_classes
        and reason_depreciation == expected_classes
        and asset_depreciation_total == 230
        and reason_depreciation_total == 230
    )
    results.append(passed)
    report_invariant(
        3,
        passed,
        f"statement depreciation={depreciation_total}; Assets classes={asset_depreciation} total={asset_depreciation_total}; "
        f"Reasons classes={reason_depreciation} total={reason_depreciation_total}; expected=230",
    )

    total_assets = value_for_label(balance_sheet, "Total Assets")
    total_liabilities = value_for_label(balance_sheet, "Total Liabilities")
    contributed_capital = section_value(reasons, "CONTRIBUTED", "Balance, August 31, 2026")
    generated_capital = section_value(reasons, "GENERATED", "Balance, August 31, 2026")
    withdrawn_capital = section_value(reasons, "WITHDRAWN", "Balance, August 31, 2026")
    total_capital = contributed_capital + generated_capital + withdrawn_capital
    passed = (
        total_assets == 4500
        and total_liabilities == 0
        and contributed_capital == 2290
        and generated_capital == 2810
        and withdrawn_capital == -600
        and total_capital == 4500
        and total_assets == total_liabilities + total_capital
    )
    results.append(passed)
    report_invariant(
        4,
        passed,
        f"Assets={total_assets}; Liabilities={total_liabilities}; capital={contributed_capital}+{generated_capital}{withdrawn_capital:+}={total_capital}; expected equation=4500=0+4500",
    )

    ar_june = value_for_label(balance_sheet, "Accounts Receivable", column=3)
    ar_august = value_for_label(balance_sheet, "Accounts Receivable", column=4)
    receivables_increase = ar_august - ar_june
    deposit_june = value_for_label(balance_sheet, "Customer Deposit", column=3)
    deposit_august = value_for_label(balance_sheet, "Customer Deposit", column=4)
    deposit_released = deposit_june - deposit_august
    operating_total = value_for_label(cash_flow, "Cash from operating activities")
    indirect_total = net_income - receivables_increase - deposit_released + depreciation_total
    passed = (
        net_income == 2640
        and receivables_increase == 300
        and deposit_released == 220
        and depreciation_total == 230
        and indirect_total == 2350
        and operating_total == 2350
    )
    results.append(passed)
    report_invariant(
        5,
        passed,
        f"{net_income}-{receivables_increase}-{deposit_released}+{depreciation_total}={indirect_total}; Cash Flow operating={operating_total}; expected=2350",
    )

    return all(results)


def emit(data: dict[str, Any], output_path: Path) -> None:
    payload = json.dumps(data, ensure_ascii=False, allow_nan=False, indent=2)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        f"{BANNER}\nwindow.BR_STMT_DATA = {payload};\n", encoding="utf-8"
    )


def main() -> int:
    args = parse_args()
    try:
        data = extract_all(Path(args.source_dir))
        if args.verify and not verify(data):
            print("Verification failed; output was not emitted.", file=sys.stderr)
            return 1
        emit(data, Path(args.out))
        print(f"Wrote {args.out}")
        return 0
    except (ExtractionError, OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
